# Yêu cầu thư viện lưu log vào một file tên là client-history.log
org.slf4j.simpleLogger.logFile=client-history.log
# Bật hiển thị thời gian
org.slf4j.simpleLogger.showDateTime=true
# Định dạng thời gian (Năm-Tháng-Ngày Giờ:Phút:Giây)
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss